# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Edit3DiSchematisation
                                 A QGIS plugin
 Edit3DiSchematisation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-03-11
        copyright            : (C) 2019 by Nelen en Schuurmans
        email                : ivar.lokhorst@nelen-schuurmans.nl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Edit3DiSchematisation class from file Edit3DiSchematisation.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Edit3DiSchematisation import Edit3DiSchematisation
    return Edit3DiSchematisation(iface)
