# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ThreeDiRasterAligner
                                 A QGIS plugin
 later added
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-01-13
        copyright            : (C) 2021 by Chris Kerklaan | Nelen & Schuurmans
        email                : chris.kerklaan@nelen-schuurmans.nl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Chris Kerklaan | Nelen & Schuurmans'
__date__ = '2021-01-13'
__copyright__ = '(C) 2021 by Chris Kerklaan | Nelen & Schuurmans'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ThreeDiRasterAligner class from file ThreeDiRasterAligner.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ThreeDiRasterAligner import ThreeDiRasterAlignerPlugin
    return ThreeDiRasterAlignerPlugin(iface)
