# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ThreeDiRasterAligner
                                 A QGIS plugin
 later added
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-01-13
        copyright            : (C) 2021 by Chris Kerklaan | Nelen & Schuurmans
        email                : chris.kerklaan@nelen-schuurmans.nl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Chris Kerklaan | Nelen & Schuurmans'
__date__ = '2021-01-13'
__copyright__ = '(C) 2021 by Chris Kerklaan | Nelen & Schuurmans'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterFileDestination,
                       QgsProcessingParameterBoolean,
                       QgsProcessingParameterNumber,
                       QgsRasterLayer,
                       QgsProject)

# import algorithm
from .raster_align_scripts.raster import Raster


class ThreeDiRasterAlignerAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.INPUT,
                self.tr('Input raster')
            )
        )

        self.addParameter(
            QgsProcessingParameterRasterLayer(
                'template_raster',
                self.tr('Template raster')
            )
        )
        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT,
                self.tr('Output raster'),
                'TIF files (*.tif)'
            )
        )
        
        
        self.align_nodata = self.addParameter(
            QgsProcessingParameterBoolean(
                'align_nodata',
                self.tr('Align data/nodata locations'),
                True,
                )
            
            )
        
        self.fill_value = self.addParameter(
             QgsProcessingParameterNumber(
                'fill_value',
                self.tr('Fill value'),
                QgsProcessingParameterNumber.Double
            )
        )
        
                    

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        input_raster_fn = self.parameterAsRasterLayer(parameters, self.INPUT, context).source()
        template_raster_fn = self.parameterAsRasterLayer(parameters, 'template_raster', context).source()
        raster_output_fn = self.parameterAsFileOutput(parameters, self.OUTPUT, context)
        align_nodata = self.parameterAsBool(parameters, 'align_nodata', context)
        fill_value= self.parameterAsDouble(parameters, 'fill_value', context)
        
        feedback.pushInfo('Loading processing parameters')
        feedback.pushInfo(f'Input raster:{input_raster_fn}')
        feedback.pushInfo(f'Template raster:{template_raster_fn}')
        feedback.pushInfo(f'Output raster:{raster_output_fn}')
        feedback.pushInfo(f'Align nodata:{align_nodata}')
        feedback.pushInfo(f'Fill Value:{fill_value}')
        
        print('Start aligning')
        template = Raster(template_raster_fn)
        raster_to_be_aligned = Raster(input_raster_fn)
    
        aligned = raster_to_be_aligned.align(
            template,
            nodata_align=align_nodata, 
            fill_value=fill_value, 
            quiet=False,
            qgs_feedback=feedback
        )
        
        # set progress
        feedback.setProgress(75)
        aligned.write(raster_output_fn, copy=True)
        feedback.setProgress(100)
    
        aligned = None
        template = None
        raster_to_be_aligned = None
        
        
        root = QgsProject.instance().layerTreeRoot()
        qgslayer = QgsRasterLayer(raster_output_fn, 'Freshly aligned raster')
        QgsProject.instance().addMapLayer(qgslayer)
        root.addLayer(qgslayer)
        
        
        # Compute the number of steps to display within the progress bar and
        # get features from source
        # total = 100.0 / source.featureCount() if source.featureCount() else 0
        # features = source.getFeatures()

        # for current, feature in enumerate(features):
        #     # Stop the algorithm if cancel button has been clicked
        #     if feedback.isCanceled():
        #         break

        #     # Add a feature in the sink
        #     sink.addFeature(feature, QgsFeatureSink.FastInsert)

        #     # Update the progress bar
        #     feedback.setProgress(int(current * total))

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return {self.OUTPUT: raster_output_fn}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Raster Aligner'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ''

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return ThreeDiRasterAlignerAlgorithm()
