# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ThreeDiRasterAligner
                                 A QGIS plugin
 later added
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-01-13
        copyright            : (C) 2021 by Chris Kerklaan | Nelen & Schuurmans
        email                : chris.kerklaan@nelen-schuurmans.nl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 
 see https://www.qgistutorials.com/en/docs/3/processing_python_plugin.html
"""

__author__ = 'Chris Kerklaan | Nelen & Schuurmans'
__date__ = '2021-01-13'
__copyright__ = '(C) 2021 by Chris Kerklaan | Nelen & Schuurmans'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.PyQt.QtWidgets import QAction
from qgis.PyQt.QtGui import QIcon

from qgis.core import QgsProcessingAlgorithm, QgsApplication
import processing
from .ThreeDiRasterAligner_provider import ThreeDiRasterAlignerProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class ThreeDiRasterAlignerPlugin(object):

    def __init__(self, iface):
        self.provider = "Raster tools"
        self.iface = iface
        
    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = ThreeDiRasterAlignerProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()
        icon = os.path.join(os.path.join(cmd_folder, 'logo.png'))
        self.action = QAction(
            QIcon(icon),
            u"Raster Alignment", self.iface.mainWindow())
        self.action.triggered.connect(self.run)
        self.iface.addPluginToMenu(u"&Threedi Raster Alignment", self.action)
        self.iface.addToolBarIcon(self.action)
        
        
    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
        self.iface.removePluginMenu(u"&Threedi Raster Alignment", self.action)
        self.iface.removeToolBarIcon(self.action)
        
    def run(self):
        processing.execAlgorithmDialog("Threedi Raster Tools:Raster Aligner")
