# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CrestLevelSampler
                                 A QGIS plugin
 Derive obstacle crest level from DEM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-10-25
        copyright            : (C) 2021 by Nelen & Schuurmans
        email                : leendert.vanwolfswinkel@nelen-schuurmans.nl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Nelen & Schuurmans'
__date__ = '2021-10-25'
__copyright__ = '(C) 2021 by Nelen & Schuurmans'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CrestLevelSampler class from file CrestLevelSampler.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .crestlevelsampler import CrestLevelSamplerPlugin
    return CrestLevelSamplerPlugin()
