# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RasterAligner
                                 A QGIS plugin
 Aligns multiple rasters
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-01-06
        copyright            : (C) 2021 by Chris Kerklaan
        email                : chris.kerklaan@nelen-schuurmans.nl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


#from raster_align import dependencies
#dependencies.ensure_everything_installed()

#dependencies.show_installed_dependencies_in_qgis()


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RasterAligner class from file RasterAligner.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .raster_align import RasterAligner
    return RasterAligner(iface)
