# -*- coding: utf-8 -*-
"""
/***************************************************************************
 threediresultstyler
                                 A QGIS plugin
 This plugin helps you style your 3Di results for better analytics
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-06-06
        copyright            : (C) 2019 by Emiel Verstegen, Nelen & Schuurmans
        email                : emiel.verstegen@nelen-schuurmans.nl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load threediresultstyler class from file threediresultstyler.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .threediresultstyler import threediresultstyler

    return threediresultstyler(iface)
