# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PipeLevelCalculator
                                 A QGIS plugin
 Calculates pipe levels based on a basic design with diameters and a DEM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-05-28
        copyright            : (C) 2020 by Emile de Badts
        email                : emile.debadts@nelen-schuurmans.nl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
from pipe_level_calculator import dependencies
dependencies.ensure_everything_installed()
dependencies.show_installed_dependencies_in_qgis()
# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PipeLevelCalculator class from file PipeLevelCalculator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pipe_level_calculator import PipeLevelCalculator
    return PipeLevelCalculator(iface)
